---
- name: Install and Enable AutoFS
  hosts: all
  become: yes

  tasks:
    - name: Installing AutoFS Package
      yum:
        name: autofs
        state: present

    - name: Ensuring autofs.service is Enabled at Boot
      systemd:
        name: autofs
        enabled: yes
        state: started
